app/devsearch/urls.py
from django.contrib import admin
from django.urls import path, include


handler404 = 'inventory.views.custom_404'

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('inventory.urls')),
]

app/inventory/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views


urlpatterns = [
    path('', views.MainPage.as_view(), name='home'), # Начальная страница
    path('accounts/login/', views.UserLogin.as_view(), name='login'), # Авторизация
    path('logout/', views.logout_view, name='logout'), # Для выхода из аккаунта
    path('computers/', views.computers_list, name='computers'), # Список компьютеров
    path('printers/', views.printers_list, name='printers'), # Список принтеров
    path('accessories/', views.accessories_list, name='accessories'), # Список периферии
    path('add-device/', views.add_device, name='add-device'), # Добавление устройств
    path('export_computers_xls/', views.export_computers_xls), # Сформирование отчёта в XLS файл
    path('export_printers_xls/', views.export_printers_xls), # Сформирование отчёта в XLS файл
    path('computer/<slug:computer_slug>/update', views.computer_update, name='computer-update'), # Обновление данных компьютеров
    path('printer/<slug:printer_slug>/update', views.printer_update, name='printer-update'), # Обновление данных принтеров
    path('accessory/<slug:device_slug>/update', views.accessory_update, name='accessory-update'), # Обновление данных принтеров
    path('computer/<slug:computer_slug>/delete', views.ComputerDelete.as_view(), name='computer-delete'), # Удаление компьютера
    path('printer/<slug:printer_slug>/delete', views.PrinterDelete.as_view(), name='printer-delete'), # Удаление принтера
    path('accessory/<slug:device_slug>/delete', views.AccessoryDelete.as_view(), name='accessory-delete'), # Удаление принтера
    path('media/', views.saved_reports, name='saved-reports'), # Список сформированных отчётов
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/inventory/models.py
from django.db import models
from datetime import date
from django.contrib.auth.models import User
from django.utils.text import slugify

# Модель для компьютеров
class Computer(models.Model):
    '''ПК и ноутбуки'''
    computer_id = models.AutoField(primary_key=True)
    ComputerType = [
        ('Компьютер настольный', 'Компьютер настольный'),
        ('Компьютер HP P3500MT', 'Компьютер HP P3500MT'),
        ('Компьютер HP Pro 3500MT QB294EA с монитором', 'Компьютер HP Pro 3500MT QB294EA с монитором'),
        ('Моноблок HP P3520', 'Моноблок HP P3520'),
        ('Нетбук Prestigio MultiPad Wize 3341 3G', 'Нетбук Prestigio MultiPad Wize 3341 3G'),
        ('Ноутбук B6M12EA HP Probook 4540s', 'Ноутбук B6M12EA HP Probook 4540s'),
        ('Ноутбук LENOVO G500', 'Ноутбук LENOVO G500'),
        ('Ноутбук LENOVO', 'Ноутбук LENOVO'),
        ('Ноутбук для XDCAM Камкордеров', 'Ноутбук для XDCAM Камкордеров'),
        ('Рабочая станция HP ProDesk 400 с монитором HP Pro', 'Рабочая станция HP ProDesk 400 с монитором HP Pro'),
        ('Системный блок HP Pavilion 500-129er', 'Системный блок HP Pavilion 500-129er'),
        ('Системный блок Apple', 'Системный блок Apple'),
        ('Монитор Аpple', 'Монитор Аpple'),
        ('19-дюймовый монитор ПК', '19-дюймовый монитор ПК'),
        ('Монитор Acer/G236HLBbd/23', 'Монитор Acer/G236HLBbd/23'),
        ('Монитор HP Z23i23-Inch IPS Monitor D7Q13A4', 'Монитор HP Z23i23-Inch IPS Monitor D7Q13A4'),
    ]
    computer_type = models.CharField("Тип компьютера", choices=ComputerType, max_length=100)
    computer_inventory = models.CharField("Инвентарный номер", max_length=9)
    computer_snumber = models.CharField("Серийный номер", max_length=50, blank=True, null=True)
    computer_location = models.CharField("Расположение", max_length=50)
    computer_date = models.DateField("Дата добавления", default=date.today)
    slug = models.SlugField(max_length=9, unique=True, db_index=True, verbose_name="URL", blank=True)
    computer_author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='computers')
   
    def __str__(self):
        return self.computer_inventory
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.computer_inventory)  # генерируем slug на основе computer_inventory
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'ПК и ноутбук'
        verbose_name_plural = 'ПК и ноутбуки'

# Модель для принтеров и сканеров
class Printer(models.Model):
    '''Принтеры и сканеры'''
    printers_id = models.AutoField(primary_key=True)
    PrinterType = [
        ('МФУ HP LaserJet 1536dnf', 'МФУ HP LaserJet 1536dnf'),
        ('МФУ HP LaserJet Pro M225dn', 'МФУ HP LaserJet Pro M225dn'),
        ('Принтер HP LaserJet Pro P1606n', 'Принтер HP LaserJet Pro P1606n'),
        ('МФУ HP Laser Jet Pro M426fdn', 'МФУ HP Laser Jet Pro M426fdn'),
        ('Принтер HP Color LaserJet CP5225dn', 'Принтер HP Color LaserJet CP5225dn'),
        ('МФУ HP LaserJet Pro4103fdn', 'МФУ HP LaserJet Pro4103fdn'),
        ('МФУ HP LaserJet M443nda', 'МФУ HP LaserJet M443nda'),
        ('Canon МФУ IR2520, 3796B003AC', 'Canon МФУ IR2520, 3796B003AC'),
        ('Принтер Epson Stylus L1300 Color', 'Принтер Epson Stylus L1300 Color'),
        ('Принтер этикеток TSP TTP-244CE', 'Принтер этикеток TSP TTP-244CE'),
        ('МФУ Canon IR2530i', 'МФУ Canon IR2530i'),
        ('Лазерный факс Panasonic KX-FL423RU-B', 'Лазерный факс Panasonic KX-FL423RU-B'),
        ('Сканер Plustek Smart Office PL 806. A4', 'Сканер Plustek Smart Office PL 806. A4'),
        ('Canon МФУ IR2520', 'Canon МФУ IR2520')
    ]
    printer_type = models.CharField("Наименование устройства", choices=PrinterType, max_length=150)
    printer_inventory = models.CharField("Инвентарный номер", max_length=9)
    printer_snumber = models.CharField("Серийный номер", max_length=50, blank=True, null=True)
    printer_location = models.CharField("Расположение", max_length=50)
    printer_date = models.DateField("Дата добавления", default=date.today)
    slug = models.SlugField(max_length=9, unique=True, db_index=True, verbose_name="URL", blank=True)
    printer_author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='printers')

    def __str__(self):
        return self.printer_inventory
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.printer_inventory)  # генерируем slug на основе printer_inventory
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Принтер и сканер'
        verbose_name_plural = 'Принтеры и сканеры'

# Модель для периферии
class Accessory(models.Model):
    '''Периферия'''
    accessory_id = models.AutoField(primary_key=True)
    accessory_type = models.CharField("Наименование устройства", max_length=100)
    accessory_inventory = models.CharField("Инвентарный номер", max_length=9)
    accessory_snumber = models.CharField("Серийный номер", max_length=50, blank=True, null=True)
    accessory_location = models.CharField("Расположение", max_length=50)
    accessory_date = models.DateField("Дата добавления", default=date.today)
    slug = models.SlugField(max_length=9, unique=True, db_index=True, verbose_name="URL", blank=True)
    accessory_author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='accessories')

    def __str__(self):
        return self.accessory_inventory
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.accessory_inventory)  # генерируем slug на основе printer_inventory
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Периферия'
        verbose_name_plural = 'Периферия'

# Модель для сохранения отчётов
class ReportLog(models.Model):
    '''Сохранение отчётов'''
    report_name = models.CharField(max_length=255)
    generated_at = models.DateTimeField(auto_now_add=True)
    file_path = models.FileField(upload_to='reports/')

    def __str__(self):
        return f"{self.report_name} ({self.generated_at})"

app/inventory/forms.py
from django import forms
from .models import Computer, Printer, Accessory


class MyComputerForm(forms.ModelForm):
    class Meta:
        model = Computer
        fields = ['computer_type', 'computer_inventory', 'computer_snumber', 'computer_location']
        widgets = {
            'computer_type': forms.Select(attrs={'class': 'form-control'}),
            'computer_inventory': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите инвентарный номер'}),
            'computer_snumber': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите серийный номер'}),
            'computer_location': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите расположение'}),
        }


class MyPrinterForm(forms.ModelForm):
    class Meta:
        model = Printer
        fields = ['printer_type', 'printer_inventory', 'printer_snumber', 'printer_location']
        widgets = {
            'printer_type': forms.Select(attrs={'class': 'form-control'}),
            'printer_inventory': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите инвентарный номер'}),
            'printer_snumber': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите серийный номер'}),
            'printer_location': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите расположение'}),
        }

class MyAccessoryForm(forms.ModelForm):
    class Meta:
        model = Accessory
        fields = ['accessory_type', 'accessory_inventory', 'accessory_snumber', 'accessory_location']
        widgets = {
            'accessory_type': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите наименование устройства'}),
            'accessory_inventory': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите инвентарный номер'}),
            'accessory_snumber': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите серийный номер'}),
            'accessory_location': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите расположение'}),
        }

app/inventory/templates/inventory/accessory-list.html
{% extends 'inventory/base.html' %}

{% block topic %}
  <div class="header-container d-flex align-items-center justify-content-between">
    <h5>Список периферийный устройств</h5>
    <!-- Поиск устройств -->
    <div class="search-group d-flex align-items-center" style="gap: 1rem;">
      <form method="get">
        <div class="input-group" style="width: 250px;">
          <input type="text" class="form-control" name="query" value="{{ query }}" placeholder="Поиск устройства" aria-describedby="button-addon2" />
          <button class="btn btn-outline-secondary" type="submit" id="button-addon2">
            <i class="bi bi-search"></i>
          </button>
        </div>
      </form>
      <!-- Отчёт -->
      <button class="btn btn-success" type="submit">
        <a href="/export_accessories_xls" class="download-list">Отчёт XLS</a>
      </button>
    </div>
  </div>
{% endblock %}

{% block content%}
  <!-- Таблица устройств -->
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Тип устройства</th>
        <th scope="col">Инвентарный код</th>
        <th scope="col">Серийный номер</th>
        <th scope="col" style=" vertical-align: middle;">
          <div style="display: inline-flex; align-items: center;">
            <span>Расположение</span>
            <div class="dropdown">
              <button type="button" data-bs-toggle="dropdown" title="Фильтр" style="border: none; background: none; padding: 0; color: inherit;">
                <i class="bi bi-funnel"></i>
              </button>
              <!-- Выпадающее меню Расположение -->
              <ul class="dropdown-menu">
                {% for loc in locations %}
                <li><a class="dropdown-item" href="?location={{ loc }}">{{ loc }}</a></li>
                {% endfor %}
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'accessories' %}">Сброс</a></li>
              </ul>
            </div>
          </div>
        </th>
        <th scope="col">Добавил</th>
        <th scope="col">Дата добавления</th>
      </tr>
    </thead>
    <tbody>
      {% for accessory in accessories %}
      <tr>
        <td>{{ accessory.accessory_type }}</td>
        <td>{{ accessory.accessory_inventory }}</td>
        <td>{{ accessory.accessory_snumber }}</td>
        <td>{{ accessory.accessory_location }}</td>
        <td>{{ accessory.accessory_author.username }}</td>
        <td style="color: gray;">{{ accessory.accessory_date }}</td>
        <td>
          <!-- Кнопки редактирования и удаления -->
          {% load custom_filters %}
          {% if user|belongs_to_group:"Editor" or user|belongs_to_group:"Admin" %}
          <li class="list-inline-item">
            <a href="{% url 'accessory-update' accessory.slug %}"><button class="btn btn-warning btn-sm rounded-0" type="button" data-toggle="tooltip" data-placement="top" title="Исправить"><i class="bi bi-pencil-square"></i></button></a>
          </li>
          <li class="list-inline-item">
            <button class="btn btn-danger btn-sm rounded-0" type="button" data-bs-toggle="modal" data-bs-target="#exampleModal" data-toggle="tooltip" data-placement="top" title="Удалить"><i class="bi bi-trash-fill"></i></button>
          </li>
          {% endif %}
        </td>
      </tr>
      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-sm">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              Удалить устройство?
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
              <form action="{% url 'accessory-delete' accessory.slug %}" method="post">
              {% csrf_token %}
                <button type="submit" class="btn btn-primary">Удалить</button></a>
            </div>
          </div>
        </div>
      </div>
      {% empty %}
      <tr>
        <td colspan="1">Ничего не найдено</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

app/inventory/templates/inventory/accessory-update.html
{% extends 'inventory/base.html' %}

{% block topic %}
    <div class="header-container">
        <h5>Устройство</h5>
    </div>
{% endblock %}

{% block content%}
    <form id="updateAccessoryForm" method="post">
        {% csrf_token %}
        {{ accessory_form.as_p }}
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
    {% if messages %}
        <div class="messages">
            {% for message in messages %}
                <div class="alert alert-success">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
    {% endif %}
{% endblock %}

app/inventory/templates/inventory/add-device.html
{% extends 'inventory/base.html' %}

{% block topic %}
    <div class="header-container">
        <h5>Добавить устройство</h5>
    </div>
{% endblock %}

{% block content%}
    <div class="mb-3">
        <label for="deviceType" class="form-label">Выберите тип устройства</label>
        <select id="deviceType" class="form-select">
            <option value="">-- Выберите тип --</option>
            <option value="computer">Компьютер</option>
            <option value="printer">Принтер</option>
            <option value="accessory">Периферия</option>
        </select>
    </div>

    <!-- Форма для компьютеров -->
    <form id="computerForm" class="hidden" method="post">
        {% csrf_token %}
        {{ computer_form.as_p }}
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>

    <!-- Форма для принтеров -->
    <form id="printerForm" class="hidden" method="post">
        {% csrf_token %}
        {{ printer_form.as_p }}
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>

    <!-- Форма для периферии -->
    <form id="accessoryForm" class="hidden" method="post">
        {% csrf_token %}
        {{ accessory_form.as_p }}
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
    
    {% if messages %}
        <div class="messages">
            {% for message in messages %}
                <div class="alert alert-success" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
    {% endif %}
{% endblock %}

{% block scripts %}
<script>
    $('#id_printer_type').select2({
        theme: "bootstrap-5",
    } );
    $('#id_computer_type').select2({
        theme: "bootstrap-5",
    } );
</script>
{% endblock %}

app/inventory/templates/inventory/computer-list.html
{% extends 'inventory/base.html' %}

{% block topic %}
  <div class="header-container d-flex align-items-center justify-content-between">
    <h5>Список ПК и ноутбуков</h5>
    <!-- Поиск устройств -->
    <div class="search-group d-flex align-items-center" style="gap: 1rem;">
      <form method="get">
        <div class="input-group" style="width: 250px;">
          <input type="text" class="form-control" name="query" value="{{ query }}" placeholder="Поиск устройства" aria-describedby="button-addon2" />
          <button class="btn btn-outline-secondary" type="submit" id="button-addon2">
            <i class="bi bi-search"></i>
          </button>
        </div>
      </form>
      <!-- Отчёт -->
      <button class="btn btn-success" type="submit">
        <a href="/export_computers_xls" class="download-list">Отчёт XLS</a>
      </button>
    </div>
  </div>
{% endblock %}

{% block content%}
  <!-- Таблица устройств -->
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Тип устройства</th>
        <th scope="col">Инвентарный код</th>
        <th scope="col">Серийный номер</th>
        <th scope="col" style=" vertical-align: middle;">
          <div style="display: inline-flex; align-items: center;">
            <span>Расположение</span>
            <div class="dropdown">
              <button type="button" data-bs-toggle="dropdown" title="Фильтр" style="border: none; background: none; padding: 0; color: inherit;">
                <i class="bi bi-funnel"></i>
              </button>
              <!-- Выпадающее меню Расположение -->
              <ul class="dropdown-menu">
                {% for loc in locations %}
                <li><a class="dropdown-item" href="?location={{ loc }}">{{ loc }}</a></li>
                {% endfor %}
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'computers' %}">Сброс</a></li>
              </ul>
            </div>
          </div>
        </th>
        <th scope="col">Добавил</th>
        <th scope="col">Дата добавления</th>
      </tr>
      
    </thead>
    <tbody>
      {% for computer in computers %}
      <tr>
        <td>{{ computer.computer_type }}</td>
        <td>{{ computer.computer_inventory }}</td>
        <td>{{ computer.computer_snumber }}</td>
        <td>{{ computer.computer_location }}</td>
        <td>{{ computer.computer_author.username }}</td>
        <td style="color: gray;">{{ computer.computer_date }}</td>
        <td>
          <!-- Кнопки редактирования и удаления -->
          {% load custom_filters %}
          {% if user|belongs_to_group:"Editor" or user|belongs_to_group:"Admin" %}
          <li class="list-inline-item">
            <a href="{% url 'computer-update' computer.slug %}"><button class="btn btn-warning btn-sm rounded-0" type="button" data-toggle="tooltip" data-placement="top" title="Исправить"><i class="bi bi-pencil-square"></i></button></a>
          </li>
          <li class="list-inline-item">
            <button class="btn btn-danger btn-sm rounded-0" type="button" data-bs-toggle="modal" data-bs-target="#exampleModal" data-toggle="tooltip" data-placement="top" title="Удалить"><i class="bi bi-trash-fill"></i></button>
          </li>
          {% endif %}
        </td>
      </tr>
      <!-- Модальное окно -->
      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-sm">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              Удалить устройство?
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
              <form action="{% url 'computer-delete' computer.slug %}" method="post">
              {% csrf_token %}
                <button type="submit" class="btn btn-primary">Удалить</button></a>
            </div>
          </div>
        </div>
      </div>
      {% empty %}
      <tr>
        <td colspan="1">Ничего не найдено</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

app/inventory/templates/inventory/computer-update.html
{% extends 'inventory/base.html' %}

{% block topic %}
    <div class="header-container">
        <h5>Устройство</h5>
    </div>
{% endblock %}

{% block content%}
    <form id="updateComputerForm" method="post">
        {% csrf_token %}
        {{ computer_form.as_p }}
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
    {% if messages %}
        <div class="messages">
            {% for message in messages %}
                <div class="alert alert-success">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
    {% endif %}
{% endblock %}

app/inventory/templates/inventory/index.html
{% extends 'inventory/base.html' %}

{% block topic %}
    <div class="header-container">
        <h5>Инструменты</h5>
    </div>
{% endblock %}

{% block content%}
    {% load custom_filters %}
    {% if user|belongs_to_group:"Editor" or user|belongs_to_group:"Admin" %}
    <div class="row">
        <div class="col-sm-6">
            <div class="card custom-card">
                <div class="card-body">
                    <h5 class="card-title">Добавить устройство</h5>
                    <p class="card-text">---</p>
                    <a href="{% url 'add-device' %}" class="btn btn-primary">Добавить</a>
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="card custom-card">
                <div class="card-body">
                    <h5 class="card-title">---</h5>
                    <p class="card-text">---</p>
                    <a href="#" class="btn btn-primary">---</a>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
{% endblock %}

app/inventory/templates/inventory/printer-update.html
{% extends 'inventory/base.html' %}

{% block topic %}
    <div class="header-container">
        <h5>Устройство</h5>
    </div>
{% endblock %}

{% block content%}
    <form id="updatePrinterForm" method="post">
        {% csrf_token %}
        {{ printer_form.as_p }}
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
    {% if messages %}
        <div class="messages">
            {% for message in messages %}
                <div class="alert alert-success">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
    {% endif %}
{% endblock %}

app/inventory/templates/inventory/saved-reports.html
{% extends 'inventory/base.html' %}

{% block topic %}
    <div class="header-container">
        <h5>Сохраненные отчёты</h5>
    </div>
{% endblock %}

{% block content%}
    <ul>
        {% for report in reports %}
            <li>
                {{ report.report_name }} ({{ report.generated_at }}): 
                <a href="{{ report.file_path }}" download>Скачать</a>
            </li>
        {% empty %}
            <li>Нет доступных отчётов.</li>
        {% endfor %}
    </ul>
{% endblock %}